name: Deploy to Azure

on:

  workflow_dispatch:

  push:

    branches:

      - main

permissions:

  id-token: write

  contents: read

env:

  IMAGE_NAME: fleet-ping

jobs:

  deploy:

    runs-on: ubuntu-latest

    environment: production

    steps:

      - name: Checkout

        uses: actions/checkout@v4

      - name: Setup Node

        uses: actions/setup-node@v4

        with:

          node-version: 22

          cache: npm

      - name: Install Dependencies

        run: npm ci

      - name: Build Docker Image

        run: |

          docker build \
            -t $IMAGE_NAME:${{ github.sha }} .

      - name: Azure Login

        uses: azure/login@v2

        with:

          client-id: ${{ secrets.AZURE_CLIENT_ID }}

          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry

        run: |

          az acr login \
            --name ${{ secrets.ACR_NAME }}

      - name: Tag Docker Image

        run: |

          docker tag \
            $IMAGE_NAME:${{ github.sha }} \
            ${{ secrets.ACR_NAME }}.azurecr.io/$IMAGE_NAME:${{ github.sha }}

      - name: Push Docker Image

        run: |

          docker push \
            ${{ secrets.ACR_NAME }}.azurecr.io/$IMAGE_NAME:${{ github.sha }}

      - name: Setup Terraform

        uses: hashicorp/setup-terraform@v3

        with:

          terraform_version: 1.8.5

      - name: Terraform Init

        working-directory: terraform

        run: terraform init

      - name: Terraform Validate

        working-directory: terraform

        run: terraform validate

      - name: Terraform Plan

        working-directory: terraform

        run: terraform plan

      - name: Deploy Container App

        run: |

          az containerapp update \
            --name fleet-ping-dev-app \
            --resource-group fleet-ping-dev-rg \
            --image \
            ${{ secrets.ACR_NAME }}.azurecr.io/$IMAGE_NAME:${{ github.sha }}
